Feature/users account
Applifort/task-manager pull request #14
Opened 2020-03-03 06:36 UTC by Applifort

2020-03-03 17:16 UTC, Andrew8xx8 requested changes

2020-03-03 17:16 UTC, Andrew8xx8 commented on app/controllers/admin/users_controller.rb
> +    @users = @q.result.order(:type).order(:id).page(params[:page]).per(10)
Число следует вынести в константу

2020-03-03 17:16 UTC, Andrew8xx8 commented on db/seeds.rb
> +60.times do |i|
Два раза не получится запустить сиды, в блоке ниже sample.new нужно заменить на `find_or_initialize_by`

2020-03-03 17:16 UTC, Andrew8xx8 commented on db/seeds.rb
> +admin = Admin.find_or_create_by(first_name: 'admin', last_name: 'admin', email: 'admin@ru.ru')
Нужно заменить на `find_or_initialize_by`

2020-03-05 11:26 UTC, artempartos commented
👍

2020-03-20 05:41 UTC, merged